name: Auto Port ROM (Artifact)

# Trigger manual dengan input link
on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Link Direct Base ROM (mido)'
        required: true
      port_url:
        description: 'Link Direct Port ROM (Infinity X)'
        required: true
      release_name:
        description: 'Nama file hasil porting (tanpa .zip)'
        required: true
        default: 'Port-InfinityX-Mido'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kosongkan Storage Server (Mencegah out of space)
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        df -h

    - name: Setup & Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip curl

    - name: Download Base ROM (mido)
      run: |
        echo "Mendownload Base ROM..."
        # Menggunakan -sL (silent) agar log download tidak nge-spam dan bikin HP lag/black screen
        curl -sL "${{ github.event.inputs.base_url }}" -o base.zip

    - name: Download Port ROM (Infinity X)
      run: |
        echo "Mendownload Port ROM..."
        curl -sL "${{ github.event.inputs.port_url }}" -o port.zip

    - name: Ekstrak ROM
      run: |
        mkdir -p base_folder port_folder
        echo "Mengekstrak Base ROM..."
        unzip -q base.zip -d base_folder
        echo "Mengekstrak Port ROM..."
        unzip -q port.zip -d port_folder

    - name: Proses Porting (Oplos Partisi System)
      run: |
        echo "Menghapus file system lama di Base ROM..."
        rm -f base_folder/system.new.dat* 
        rm -f base_folder/system.transfer.list 
        rm -f base_folder/system.patch.dat

        echo "Memindahkan file system dari Port ROM ke Base ROM..."
        cp port_folder/system.new.dat* base_folder/
        cp port_folder/system.transfer.list base_folder/
        cp port_folder/system.patch.dat base_folder/

    - name: Hapus Device Check di Updater-Script
      run: |
        SCRIPT_PATH="base_folder/META-INF/com/google/android/updater-script"
        if [ -f "$SCRIPT_PATH" ]; then
          echo "Memodifikasi updater-script..."
          sed -i '/getprop/d' "$SCRIPT_PATH"
          sed -i '/assert/d' "$SCRIPT_PATH"
        fi

    - name: Repack menjadi Flashable Zip
      run: |
        echo "Membungkus kembali ROM..."
        cd base_folder
        # Menggunakan opsi 'q' (quiet) agar tidak mencetak ribuan nama file ke layar
        zip -r1q ../${{ github.event.inputs.release_name }}.zip ./*

    - name: Upload Hasil Porting sebagai Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ROM-Hasil-Porting
        path: ${{ github.event.inputs.release_name }}.zip
